#!/usr/bin/env bash

# ====== Variables =============================

gaps_top="4"
gaps_bottom="24"
gaps_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== List of rules =========================

# My new config (don't manage any by default, enable for main apps)
yabai -m rule --add app!="^(Brave Browser|Code|WhatsApp|Discord|Messages|Slack|Calendar|Todoist|Airmail|Notes|Notion)$" manage="off"

# Some exceptions to above
yabai -m rule --add app="^Airmail$" title="^(New Message)$" manage="off"
# If a new window is not resizable, float it
yabai -m signal --add event="window_created" \
  action="[[ \$(yabai -m query --windows --window \${YABAI_WINDOW_ID} | jq '.resizable == 0 and .floating == 0') == \"true\" ]] && yabai -m window \${YABAI_WINDOW_ID} --toggle float"

# Group some common apps into spaces
yabai -m rule --add app="^(WhatsApp|Discord|Messages|Slack)$" space=2
yabai -m rule --add app="^(Brave Browser|Code)$" space=3
yabai -m rule --add app="^(Calendar|Todoist|Airmail|Notes|Notion)$" space=4

# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

# Make Chrome Picture in Picture mode windows appear topmost and on all spaces
yabai -m rule --add app='^Google Chrome$' title='^Picture in Picture$' manage=off topmost=on sticky=on

# OLD style (manage by default, disable for some)
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
# yabai -m rule --add label="1Password" app="^1Password [0-9]+$" manage=off
# yabai -m rule --add label="Preview" app="^Preview$" manage=off
# yabai -m rule --add label="FaceTime" app="^FaceTime$" manage=off
# yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="mpv" app="^mpv$" manage=off
# yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
# yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
# yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
# yabai -m rule --add label="Tandem" app="^Tandem$" manage=off
